########################################
#                                      #
#            CLEVER SENSOR             #
#                                      #
########################################
sensor:
  - platform: rest
    name: Clever Lynladerstation Odense
    resource: https://clever-app-prod.firebaseio.com/prod/availability/V1.json
    unit_of_measurement: stik
    value_template: >
      {% set location = "f053c7a5-1616-ec11-b6e6-000d3addde22" %}
      {% set plugCount = namespace(value=0) %}
      {% for plug in value_json["clever"] %}
        {% if value_json["clever"][plug].locationId == location %}
            {% if value_json["clever"][plug].status == "Available" %}
                {% set plugCount.value = plugCount.value + 1 %}
            {% endif %}
        {% endif %}
      {% endfor %}
      {{plugCount.value}}
